//
// AddCustomerTokenRequestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.AddCustomerTokenRequestData")
public typealias AddCustomerTokenRequestData = SmartCommunicationsAPI.AddCustomerTokenRequestData

extension SmartCommunicationsAPI {

public struct AddCustomerTokenRequestData: Codable, JSONEncodable, Hashable {

    public var attributes: AddCustomerTokenRequestDataAttributes?

    public init(attributes: AddCustomerTokenRequestDataAttributes? = nil) {
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
