//
// AuthTokenResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.AuthTokenResponseData")
public typealias AuthTokenResponseData = SmartCommunicationsAPI.AuthTokenResponseData

extension SmartCommunicationsAPI {

public struct AuthTokenResponseData: Codable, JSONEncodable, Hashable {

    /** Тип данных ответа. */
    public var type: String?
    /** Идентификатор пользователя. */
    public var id: String?
    public var attributes: AuthTokenResponseDataAttributes?

    public init(type: String? = nil, id: String? = nil, attributes: AuthTokenResponseDataAttributes? = nil) {
        self.type = type
        self.id = id
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SmartCommunicationsAPI.AuthTokenResponseData: Identifiable {}
