//
// GetAuthTokenRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.GetAuthTokenRequestDataAttributes")
public typealias GetAuthTokenRequestDataAttributes = SmartCommunicationsAPI.GetAuthTokenRequestDataAttributes

extension SmartCommunicationsAPI {

public struct GetAuthTokenRequestDataAttributes: Codable, JSONEncodable, Hashable {

    /** Имя пользователя. */
    public var username: String
    /** Пароль пользователя. */
    public var password: String

    public init(username: String, password: String) {
        self.username = username
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(password, forKey: .password)
    }
}

}
