//
// GetAuthTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.GetAuthTokenRequest")
public typealias GetAuthTokenRequest = SmartCommunicationsAPI.GetAuthTokenRequest

extension SmartCommunicationsAPI {

public struct GetAuthTokenRequest: Codable, JSONEncodable, Hashable {

    public var data: GetAuthTokenRequestData?

    public init(data: GetAuthTokenRequestData? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
