//
// LogPushEvent200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.LogPushEvent200Response")
public typealias LogPushEvent200Response = SmartCommunicationsAPI.LogPushEvent200Response

extension SmartCommunicationsAPI {

public struct LogPushEvent200Response: Codable, JSONEncodable, Hashable {

    public var success: Bool?

    public init(success: Bool? = nil) {
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
    }
}

}
