//
// ModifySubscriptionRequestDataAttributesCategoriesMailingCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.ModifySubscriptionRequestDataAttributesCategoriesMailingCode")
public typealias ModifySubscriptionRequestDataAttributesCategoriesMailingCode = SmartCommunicationsAPI.ModifySubscriptionRequestDataAttributesCategoriesMailingCode

extension SmartCommunicationsAPI {

public struct ModifySubscriptionRequestDataAttributesCategoriesMailingCode: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var sms: String?
    public var push: String?
    public var messengerTelegram: String?
    public var messengerWhatsapp: String?

    public init(email: String? = nil, sms: String? = nil, push: String? = nil, messengerTelegram: String? = nil, messengerWhatsapp: String? = nil) {
        self.email = email
        self.sms = sms
        self.push = push
        self.messengerTelegram = messengerTelegram
        self.messengerWhatsapp = messengerWhatsapp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case sms
        case push
        case messengerTelegram = "messenger:telegram"
        case messengerWhatsapp = "messenger:whatsapp"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(sms, forKey: .sms)
        try container.encodeIfPresent(push, forKey: .push)
        try container.encodeIfPresent(messengerTelegram, forKey: .messengerTelegram)
        try container.encodeIfPresent(messengerWhatsapp, forKey: .messengerWhatsapp)
    }
}

}
