//
// ModifySubscriptionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.ModifySubscriptionRequest")
public typealias ModifySubscriptionRequest = SmartCommunicationsAPI.ModifySubscriptionRequest

extension SmartCommunicationsAPI {

public struct ModifySubscriptionRequest: Codable, JSONEncodable, Hashable {

    public var data: ModifySubscriptionRequestData?

    public init(data: ModifySubscriptionRequestData? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
