//
// RateLimitErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.RateLimitErrorResponse")
public typealias RateLimitErrorResponse = SmartCommunicationsAPI.RateLimitErrorResponse

extension SmartCommunicationsAPI {

public struct RateLimitErrorResponse: Codable, JSONEncodable, Hashable {

    /** Ошибки ограничения нагрузки на API. */
    public var errors: [RateLimitErrorResponseErrorsInner]?

    public init(errors: [RateLimitErrorResponseErrorsInner]? = nil) {
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
    }
}

}
