//
// SMCSuccessResponseDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.SMCSuccessResponseDataAttributes")
public typealias SMCSuccessResponseDataAttributes = SmartCommunicationsAPI.SMCSuccessResponseDataAttributes

extension SmartCommunicationsAPI {

public struct SMCSuccessResponseDataAttributes: Codable, JSONEncodable, Hashable {

    public var status: String?

    public init(status: String? = nil) {
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

}
