//
// GenerateAccessToken200ResponseLinks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GenerateAccessToken200ResponseLinks")
public typealias GenerateAccessToken200ResponseLinks = SmartCommSDKAPI.GenerateAccessToken200ResponseLinks

extension SmartCommSDKAPI {

public struct GenerateAccessToken200ResponseLinks: Codable, JSONEncodable, Hashable {

    public var _self: String?

    public init(_self: String? = nil) {
        self._self = _self
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _self = "self"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_self, forKey: ._self)
    }
}

}
