//
// GetCustomerNotificationStatus200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GetCustomerNotificationStatus200Response")
public typealias GetCustomerNotificationStatus200Response = SmartCommSDKAPI.GetCustomerNotificationStatus200Response

extension SmartCommSDKAPI {

public struct GetCustomerNotificationStatus200Response: Codable, JSONEncodable, Hashable {

    public var links: GetCustomerNotificationStatus200ResponseLinks?
    public var data: [GetCustomerNotificationStatus200ResponseDataInner]?
    public var meta: GetCustomerNotificationStatus200ResponseMeta?

    public init(links: GetCustomerNotificationStatus200ResponseLinks? = nil, data: [GetCustomerNotificationStatus200ResponseDataInner]? = nil, meta: GetCustomerNotificationStatus200ResponseMeta? = nil) {
        self.links = links
        self.data = data
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case links
        case data
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}

}
