//
// GetCustomerNotificationStatus200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GetCustomerNotificationStatus200ResponseDataInner")
public typealias GetCustomerNotificationStatus200ResponseDataInner = SmartCommSDKAPI.GetCustomerNotificationStatus200ResponseDataInner

extension SmartCommSDKAPI {

public struct GetCustomerNotificationStatus200ResponseDataInner: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var id: String?
    public var attributes: GetCustomerNotificationStatus200ResponseDataInnerAttributes?

    public init(type: String? = nil, id: String? = nil, attributes: GetCustomerNotificationStatus200ResponseDataInnerAttributes? = nil) {
        self.type = type
        self.id = id
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
