//
// GetCustomerSubscriptionCategories200ResponseLinks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GetCustomerSubscriptionCategories200ResponseLinks")
public typealias GetCustomerSubscriptionCategories200ResponseLinks = SmartCommSDKAPI.GetCustomerSubscriptionCategories200ResponseLinks

extension SmartCommSDKAPI {

public struct GetCustomerSubscriptionCategories200ResponseLinks: Codable, JSONEncodable, Hashable {

    public var first: String?
    public var last: String?

    public init(first: String? = nil, last: String? = nil) {
        self.first = first
        self.last = last
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case first
        case last
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(first, forKey: .first)
        try container.encodeIfPresent(last, forKey: .last)
    }
}

}
