//
// LogPushEventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.LogPushEventRequest")
public typealias LogPushEventRequest = SmartCommSDKAPI.LogPushEventRequest

extension SmartCommSDKAPI {

/** Тело запроса должно содержать массив статусов, где type: delivered/open/click/spam/unsubscibe,                    message_id - идентификатор сообщения, external_client_id - идентификатор клиента */
public struct LogPushEventRequest: Codable, JSONEncodable, Hashable {

    public var data: [LogPushEventRequestDataInner]?

    public init(data: [LogPushEventRequestDataInner]? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
