//
// SetCustomerNotificationStatusRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.SetCustomerNotificationStatusRequestDataAttributes")
public typealias SetCustomerNotificationStatusRequestDataAttributes = SmartCommSDKAPI.SetCustomerNotificationStatusRequestDataAttributes

extension SmartCommSDKAPI {

public struct SetCustomerNotificationStatusRequestDataAttributes: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var push: String?
    public var sms: String?

    public init(email: String? = nil, push: String? = nil, sms: String? = nil) {
        self.email = email
        self.push = push
        self.sms = sms
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case push
        case sms
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(push, forKey: .push)
        try container.encodeIfPresent(sms, forKey: .sms)
    }
}

}
