//
// AuthorizationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

extension SmartCommunicationsAPI {


open class AuthorizationAPI {

    /**
     Авторизация в системе SMC
     
     - parameter getAuthTokenRequest: (body) Учетные данные для получения токена. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAuthToken(getAuthTokenRequest: GetAuthTokenRequest, apiResponseQueue: DispatchQueue = SmartCommunicationsAPI.apiResponseQueue, completion: @escaping ((_ data: GetAuthToken200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getAuthTokenWithRequestBuilder(getAuthTokenRequest: getAuthTokenRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Авторизация в системе SMC
     - POST /token
     - Получение токена для авторизации в системе SMC.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter getAuthTokenRequest: (body) Учетные данные для получения токена. 
     - returns: RequestBuilder<GetAuthToken200Response> 
     */
    open class func getAuthTokenWithRequestBuilder(getAuthTokenRequest: GetAuthTokenRequest) -> RequestBuilder<GetAuthToken200Response> {
        let localVariablePath = "/token"
        let localVariableURLString = SmartCommunicationsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getAuthTokenRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetAuthToken200Response>.Type = SmartCommunicationsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
}
