//
// CustomerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

extension SmartCommunicationsAPI {


open class CustomerAPI {

    /**
     Передать в Смарт полученный от APNS/FCM/rustore/HuaweiPushToolkit токен
     
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - parameter addCustomerTokenRequest: (body) Тело запроса должно содержать массив контактных данных, где &#x60;type&#x60; и &#x60;value&#x60; обязательные. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addCustomerToken(id: String, addCustomerTokenRequest: AddCustomerTokenRequest? = nil, apiResponseQueue: DispatchQueue = SmartCommunicationsAPI.apiResponseQueue, completion: @escaping ((_ data: SMCSuccessResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return addCustomerTokenWithRequestBuilder(id: id, addCustomerTokenRequest: addCustomerTokenRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Передать в Смарт полученный от APNS/FCM/rustore/HuaweiPushToolkit токен
     - POST /customer/{id}/contact
     - Вставить контактные данные клиента
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - parameter addCustomerTokenRequest: (body) Тело запроса должно содержать массив контактных данных, где &#x60;type&#x60; и &#x60;value&#x60; обязательные. (optional)
     - returns: RequestBuilder<SMCSuccessResponse> 
     */
    open class func addCustomerTokenWithRequestBuilder(id: String, addCustomerTokenRequest: AddCustomerTokenRequest? = nil) -> RequestBuilder<SMCSuccessResponse> {
        var localVariablePath = "/customer/{id}/contact"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SmartCommunicationsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addCustomerTokenRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SMCSuccessResponse>.Type = SmartCommunicationsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Получить из Смарта статус разрешения на уведомления клиенту
     
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCustomerNotificationStatus(id: String, apiResponseQueue: DispatchQueue = SmartCommunicationsAPI.apiResponseQueue, completion: @escaping ((_ data: GetCustomerNotificationStatus200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getCustomerNotificationStatusWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Получить из Смарта статус разрешения на уведомления клиенту
     - GET /customer/{id}/channel
     - Возвращает разрешения на уведомления клиенту. При запросе коллекции сущностей в /GET параметрах можно передать: `?sort=[{\"attribute\": \"name\", \"direction\": \"asc\"},...]` Это JSON-массив объектов с условиями сортировки. - **attribute**: Имя атрибута модели. - **direction**: Направление сортировки. Возможные значения: `asc`, `desc`. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - returns: RequestBuilder<GetCustomerNotificationStatus200Response> 
     */
    open class func getCustomerNotificationStatusWithRequestBuilder(id: String) -> RequestBuilder<GetCustomerNotificationStatus200Response> {
        var localVariablePath = "/customer/{id}/channel"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SmartCommunicationsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetCustomerNotificationStatus200Response>.Type = SmartCommunicationsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Получить из Смарта статус подписки клиента на категории рассылок
     
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCustomerSubscriptionCategories(id: String, apiResponseQueue: DispatchQueue = SmartCommunicationsAPI.apiResponseQueue, completion: @escaping ((_ data: GetCustomerSubscriptionCategories200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getCustomerSubscriptionCategoriesWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Получить из Смарта статус подписки клиента на категории рассылок
     - GET /customer/{id}/subscribe
     - Внимание! Если клиент не подписан на какую-либо из категорий - она не будет отображаться (`data.attributes` динамическое). В случае полного отсутствия подписок у клиента - вернется пустой массив `attributes`. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - returns: RequestBuilder<GetCustomerSubscriptionCategories200Response> 
     */
    open class func getCustomerSubscriptionCategoriesWithRequestBuilder(id: String) -> RequestBuilder<GetCustomerSubscriptionCategories200Response> {
        var localVariablePath = "/customer/{id}/subscribe"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SmartCommunicationsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetCustomerSubscriptionCategories200Response>.Type = SmartCommunicationsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Передать в Смарт статус подписки на категории
     
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - parameter modifySubscriptionRequest: (body) В &#x60;categories&#x60; передаются одна или более категорий рассылок, содержащей пары ключ-значение, где ключ - это код категории рассылки (&#x60;mailingCode&#x60;), а значение - это объект, содержащий пары ключ-значение, где ключ - это тип массовых рассылок, а значение - статус подписки (&#x60;Y&#x60; - подписан, &#x60;N&#x60; - отписан, &#x60;ND&#x60; - удалить из категории).  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func modifyCustomerSubscriptionCategories(id: String, modifySubscriptionRequest: ModifySubscriptionRequest? = nil, apiResponseQueue: DispatchQueue = SmartCommunicationsAPI.apiResponseQueue, completion: @escaping ((_ data: SMCSuccessResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return modifyCustomerSubscriptionCategoriesWithRequestBuilder(id: id, modifySubscriptionRequest: modifySubscriptionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Передать в Смарт статус подписки на категории
     - PATCH /customer/{id}/subscribe
     - Метод для управления подпиской клиента по его идентификатору в мастер-системе. Подписка на категории рассылок, по которым код не передан не обновляется.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - parameter modifySubscriptionRequest: (body) В &#x60;categories&#x60; передаются одна или более категорий рассылок, содержащей пары ключ-значение, где ключ - это код категории рассылки (&#x60;mailingCode&#x60;), а значение - это объект, содержащий пары ключ-значение, где ключ - это тип массовых рассылок, а значение - статус подписки (&#x60;Y&#x60; - подписан, &#x60;N&#x60; - отписан, &#x60;ND&#x60; - удалить из категории).  (optional)
     - returns: RequestBuilder<SMCSuccessResponse> 
     */
    open class func modifyCustomerSubscriptionCategoriesWithRequestBuilder(id: String, modifySubscriptionRequest: ModifySubscriptionRequest? = nil) -> RequestBuilder<SMCSuccessResponse> {
        var localVariablePath = "/customer/{id}/subscribe"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SmartCommunicationsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: modifySubscriptionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SMCSuccessResponse>.Type = SmartCommunicationsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Передать в Смарт статус разрешения на уведомления клиенту
     
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - parameter setCustomerNotificationStatusRequest: (body) Атрибут должен содрежать пары ключ-значение, где ключ - это тип канала коммуникации,                    а значение - это статус разрешения на уведомления клиенту (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func setCustomerNotificationStatus(id: String, setCustomerNotificationStatusRequest: SetCustomerNotificationStatusRequest? = nil, apiResponseQueue: DispatchQueue = SmartCommunicationsAPI.apiResponseQueue, completion: @escaping ((_ data: SMCSuccessResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return setCustomerNotificationStatusWithRequestBuilder(id: id, setCustomerNotificationStatusRequest: setCustomerNotificationStatusRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Передать в Смарт статус разрешения на уведомления клиенту
     - POST /customer/{id}/channel
     - Изменить/добавить подписки клиента на каналы коммуникаций
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Внешний идентификатор клиента (client_external_id) 
     - parameter setCustomerNotificationStatusRequest: (body) Атрибут должен содрежать пары ключ-значение, где ключ - это тип канала коммуникации,                    а значение - это статус разрешения на уведомления клиенту (optional)
     - returns: RequestBuilder<SMCSuccessResponse> 
     */
    open class func setCustomerNotificationStatusWithRequestBuilder(id: String, setCustomerNotificationStatusRequest: SetCustomerNotificationStatusRequest? = nil) -> RequestBuilder<SMCSuccessResponse> {
        var localVariablePath = "/customer/{id}/channel"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SmartCommunicationsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setCustomerNotificationStatusRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SMCSuccessResponse>.Type = SmartCommunicationsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
}
