//
// ConfirmRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class ConfirmRequest: Codable, JSONEncodable, Hashable {

    public var popupId: Int?
    public var clientId: String?
    public var sourceId: Int?

    public init(popupId: Int? = nil, clientId: String? = nil, sourceId: Int? = nil) {
        self.popupId = popupId
        self.clientId = clientId
        self.sourceId = sourceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case popupId = "popup_id"
        case clientId = "client_id"
        case sourceId = "source_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(popupId, forKey: .popupId)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(sourceId, forKey: .sourceId)
    }

    public static func == (lhs: ConfirmRequest, rhs: ConfirmRequest) -> Bool {
        lhs.popupId == rhs.popupId &&
        lhs.clientId == rhs.clientId &&
        lhs.sourceId == rhs.sourceId
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(popupId?.hashValue)
        hasher.combine(clientId?.hashValue)
        hasher.combine(sourceId?.hashValue)
    }
}
