//
// PopupPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class PopupRequest: Codable, JSONEncodable, Hashable {

    public var clientId: String?
    public var action: String?
    public var reference: String?

    public init(clientId: String? = nil, action: String? = nil, reference: String? = nil) {
        self.clientId = clientId
        self.action = action
        self.reference = reference
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case action
        case reference
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(reference, forKey: .reference)
    }

    public static func == (lhs: PopupRequest, rhs: PopupRequest) -> Bool {
        lhs.clientId == rhs.clientId &&
        lhs.action == rhs.action &&
        lhs.reference == rhs.reference
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(clientId?.hashValue)
        hasher.combine(action?.hashValue)
        hasher.combine(reference?.hashValue)
        
    }
}

