//
// PopupStyle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class PopupResponseStyle: Codable, JSONEncodable, Hashable {

    public var mainColor: String?
    public var secondColor: String?

    public init(mainColor: String? = nil, secondColor: String? = nil) {
        self.mainColor = mainColor
        self.secondColor = secondColor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mainColor = "main_color"
        case secondColor = "second_color"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mainColor, forKey: .mainColor)
        try container.encodeIfPresent(secondColor, forKey: .secondColor)
    }

    public static func == (lhs: PopupResponseStyle, rhs: PopupResponseStyle) -> Bool {
        lhs.mainColor == rhs.mainColor &&
        lhs.secondColor == rhs.secondColor
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(mainColor?.hashValue)
        hasher.combine(secondColor?.hashValue)
    }
}
