//
// AddCustomerTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.AddCustomerTokenRequest")
public typealias AddCustomerTokenRequest = SmartCommunicationsAPI.AddCustomerTokenRequest

extension SmartCommunicationsAPI {

public struct AddCustomerTokenRequest: Codable, JSONEncodable, Hashable {

    public var data: AddCustomerTokenRequestData?

    public init(data: AddCustomerTokenRequestData? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
