//
// AuthTokenResponseDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.AuthTokenResponseDataAttributes")
public typealias AuthTokenResponseDataAttributes = SmartCommunicationsAPI.AuthTokenResponseDataAttributes

extension SmartCommunicationsAPI {

public struct AuthTokenResponseDataAttributes: Codable, JSONEncodable, Hashable {

    /** JWT токен для авторизации. */
    public var accessToken: String?
    public var user: AuthTokenResponseDataAttributesUser?

    public init(accessToken: String? = nil, user: AuthTokenResponseDataAttributesUser? = nil) {
        self.accessToken = accessToken
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accessToken, forKey: .accessToken)
        try container.encodeIfPresent(user, forKey: .user)
    }
}

}
