//
// AuthTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.AuthTokenResponse")
public typealias AuthTokenResponse = SmartCommunicationsAPI.AuthTokenResponse

extension SmartCommunicationsAPI {

public struct AuthTokenResponse: Codable, JSONEncodable, Hashable {

    public var data: AuthTokenResponseData?
    /** Массив ошибок, если они есть. */
    public var errors: [SMCErrorDetails]?
    public var links: SMCLinks?

    public init(data: AuthTokenResponseData? = nil, errors: [SMCErrorDetails]? = nil, links: SMCLinks? = nil) {
        self.data = data
        self.errors = errors
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case errors
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(links, forKey: .links)
    }
}

}
