//
// CustomerNotificationStatusDataInnerAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.CustomerNotificationStatusDataInnerAttributes")
public typealias CustomerNotificationStatusDataInnerAttributes = SmartCommunicationsAPI.CustomerNotificationStatusDataInnerAttributes

extension SmartCommunicationsAPI {

public struct CustomerNotificationStatusDataInnerAttributes: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var subtype: String?
    public var value: Int?

    public init(type: String? = nil, subtype: String? = nil, value: Int? = nil) {
        self.type = type
        self.subtype = subtype
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case subtype
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(subtype, forKey: .subtype)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

}
