//
// CustomerSubscriptionCategoriesDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.CustomerSubscriptionCategoriesDataInner")
public typealias CustomerSubscriptionCategoriesDataInner = SmartCommunicationsAPI.CustomerSubscriptionCategoriesDataInner

extension SmartCommunicationsAPI {

public struct CustomerSubscriptionCategoriesDataInner: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var id: String?
    public var attributes: CustomerSubscriptionCategoriesDataInnerAttributes?
    public var links: SMCLinks?

    public init(type: String? = nil, id: String? = nil, attributes: CustomerSubscriptionCategoriesDataInnerAttributes? = nil, links: SMCLinks? = nil) {
        self.type = type
        self.id = id
        self.attributes = attributes
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case attributes
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encodeIfPresent(links, forKey: .links)
    }
}

}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SmartCommunicationsAPI.CustomerSubscriptionCategoriesDataInner: Identifiable {}
