//
// CustomerNotificationStatusDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.CustomerNotificationStatusDataInner")
public typealias CustomerNotificationStatusDataInner = SmartCommunicationsAPI.CustomerNotificationStatusDataInner

extension SmartCommunicationsAPI {

public struct CustomerNotificationStatusDataInner: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var id: String?
    public var attributes: CustomerNotificationStatusDataInnerAttributes?

    public init(type: String? = nil, id: String? = nil, attributes: CustomerNotificationStatusDataInnerAttributes? = nil) {
        self.type = type
        self.id = id
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SmartCommunicationsAPI.CustomerNotificationStatusDataInner: Identifiable {}
