//
// CustomerNotificationStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.CustomerNotificationStatus")
public typealias CustomerNotificationStatus = SmartCommunicationsAPI.CustomerNotificationStatus

extension SmartCommunicationsAPI {

public struct CustomerNotificationStatus: Codable, JSONEncodable, Hashable {

    public var links: SMCLinks?
    public var data: [CustomerNotificationStatusDataInner]?
    public var meta: SMCMeta?

    public init(links: SMCLinks? = nil, data: [CustomerNotificationStatusDataInner]? = nil, meta: SMCMeta? = nil) {
        self.links = links
        self.data = data
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case links
        case data
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}

}
