//
// GetAuthTokenRequestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.GetAuthTokenRequestData")
public typealias GetAuthTokenRequestData = SmartCommunicationsAPI.GetAuthTokenRequestData

extension SmartCommunicationsAPI {

public struct GetAuthTokenRequestData: Codable, JSONEncodable, Hashable {

    public var attributes: GetAuthTokenRequestDataAttributes?

    public init(attributes: GetAuthTokenRequestDataAttributes? = nil) {
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
