//
// LogPushEventRequestDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.LogPushEventRequestDataInner")
public typealias LogPushEventRequestDataInner = SmartCommunicationsAPI.LogPushEventRequestDataInner

extension SmartCommunicationsAPI {

public struct LogPushEventRequestDataInner: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var messageId: String?
    public var externalClientId: String?

    public init(type: String? = nil, messageId: String? = nil, externalClientId: String? = nil) {
        self.type = type
        self.messageId = messageId
        self.externalClientId = externalClientId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case messageId = "message_id"
        case externalClientId = "external_client_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(messageId, forKey: .messageId)
        try container.encodeIfPresent(externalClientId, forKey: .externalClientId)
    }
}

}
