//
// ModifySubscriptionRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.ModifySubscriptionRequestDataAttributes")
public typealias ModifySubscriptionRequestDataAttributes = SmartCommunicationsAPI.ModifySubscriptionRequestDataAttributes

extension SmartCommunicationsAPI {

public struct ModifySubscriptionRequestDataAttributes: Codable, JSONEncodable, Hashable {

    public var categories: ModifySubscriptionRequestDataAttributesCategories?

    public init(categories: ModifySubscriptionRequestDataAttributesCategories? = nil) {
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categories, forKey: .categories)
    }
}

}
