//
// ModifySubscriptionRequestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.ModifySubscriptionRequestData")
public typealias ModifySubscriptionRequestData = SmartCommunicationsAPI.ModifySubscriptionRequestData

extension SmartCommunicationsAPI {

public struct ModifySubscriptionRequestData: Codable, JSONEncodable, Hashable {

    public var attributes: ModifySubscriptionRequestDataAttributes?

    public init(attributes: ModifySubscriptionRequestDataAttributes? = nil) {
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
