//
// RateLimitErrorResponseErrorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.RateLimitErrorResponseErrorsInner")
public typealias RateLimitErrorResponseErrorsInner = SmartCommunicationsAPI.RateLimitErrorResponseErrorsInner

extension SmartCommunicationsAPI {

public struct RateLimitErrorResponseErrorsInner: Codable, JSONEncodable, Hashable {

    /** Код состояния HTTP. */
    public var status: Int?
    /** Описание ошибки. */
    public var title: String?

    public init(status: Int? = nil, title: String? = nil) {
        self.status = status
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

}
