//
// SetCustomerNotificationStatusRequestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.SetCustomerNotificationStatusRequestData")
public typealias SetCustomerNotificationStatusRequestData = SmartCommunicationsAPI.SetCustomerNotificationStatusRequestData

extension SmartCommunicationsAPI {

public struct SetCustomerNotificationStatusRequestData: Codable, JSONEncodable, Hashable {

    public var attributes: SetCustomerNotificationStatusRequestDataAttributes?

    public init(attributes: SetCustomerNotificationStatusRequestDataAttributes? = nil) {
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
