//
// SMCLinks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.SMCLinks")
public typealias SMCLinks = SmartCommunicationsAPI.SMCLinks

extension SmartCommunicationsAPI {

/** Ссылки для навигации. Все поля (&#x60;self&#x60;, &#x60;first&#x60;, &#x60;last&#x60;) являются опциональными.  */
public struct SMCLinks: Codable, JSONEncodable, Hashable {

    /** Ссылка на текущий ресурс. */
    public var _self: String?
    public var first: String?
    public var last: String?

    public init(_self: String? = nil, first: String? = nil, last: String? = nil) {
        self._self = _self
        self.first = first
        self.last = last
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _self = "self"
        case first
        case last
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_self, forKey: ._self)
        try container.encodeIfPresent(first, forKey: .first)
        try container.encodeIfPresent(last, forKey: .last)
    }
}

}
