//
// SMCSuccessResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.SMCSuccessResponse")
public typealias SMCSuccessResponse = SmartCommunicationsAPI.SMCSuccessResponse

extension SmartCommunicationsAPI {

public struct SMCSuccessResponse: Codable, JSONEncodable, Hashable {

    public var data: SMCSuccessResponseData?

    public init(data: SMCSuccessResponseData? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
