//
// SMCSuccessResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommunicationsAPI.SMCSuccessResponseData")
public typealias SMCSuccessResponseData = SmartCommunicationsAPI.SMCSuccessResponseData

extension SmartCommunicationsAPI {

public struct SMCSuccessResponseData: Codable, JSONEncodable, Hashable {

    public var attributes: SMCSuccessResponseDataAttributes?

    public init(attributes: SMCSuccessResponseDataAttributes? = nil) {
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
