//
// AddCustomerContactTokenRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.AddCustomerContactTokenRequestDataAttributes")
public typealias AddCustomerContactTokenRequestDataAttributes = SmartCommSDKAPI.AddCustomerContactTokenRequestDataAttributes

extension SmartCommSDKAPI {

public struct AddCustomerContactTokenRequestDataAttributes: Codable, JSONEncodable, Hashable {

    public var contacts: [AddCustomerContactTokenRequestDataAttributesContactsInner]?

    public init(contacts: [AddCustomerContactTokenRequestDataAttributesContactsInner]? = nil) {
        self.contacts = contacts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contacts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contacts, forKey: .contacts)
    }
}

}
