//
// GenerateAccessToken401Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GenerateAccessToken401Response")
public typealias GenerateAccessToken401Response = SmartCommSDKAPI.GenerateAccessToken401Response

extension SmartCommSDKAPI {

public struct GenerateAccessToken401Response: Codable, JSONEncodable, Hashable {

    public var errors: [GenerateAccessToken401ResponseErrorsInner]?

    public init(errors: [GenerateAccessToken401ResponseErrorsInner]? = nil) {
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
    }
}

}
