//
// GenerateAccessToken200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GenerateAccessToken200ResponseData")
public typealias GenerateAccessToken200ResponseData = SmartCommSDKAPI.GenerateAccessToken200ResponseData

extension SmartCommSDKAPI {

public struct GenerateAccessToken200ResponseData: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var id: String?
    public var attributes: GenerateAccessToken200ResponseDataAttributes?

    public init(type: String? = nil, id: String? = nil, attributes: GenerateAccessToken200ResponseDataAttributes? = nil) {
        self.type = type
        self.id = id
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
