//
// GenerateAccessTokenRequestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GenerateAccessTokenRequestData")
public typealias GenerateAccessTokenRequestData = SmartCommSDKAPI.GenerateAccessTokenRequestData

extension SmartCommSDKAPI {

public struct GenerateAccessTokenRequestData: Codable, JSONEncodable, Hashable {

    public var attributes: GenerateAccessTokenRequestDataAttributes?

    public init(attributes: GenerateAccessTokenRequestDataAttributes? = nil) {
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
