//
// GenerateAccessToken200ResponseDataAttributesUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GenerateAccessToken200ResponseDataAttributesUser")
public typealias GenerateAccessToken200ResponseDataAttributesUser = SmartCommSDKAPI.GenerateAccessToken200ResponseDataAttributesUser

extension SmartCommSDKAPI {

public struct GenerateAccessToken200ResponseDataAttributesUser: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var username: String?
    public var email: String?

    public init(id: Int? = nil, username: String? = nil, email: String? = nil) {
        self.id = id
        self.username = username
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(email, forKey: .email)
    }
}

}
