//
// GetCustomerSubscriptionCategories200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GetCustomerSubscriptionCategories200ResponseDataInner")
public typealias GetCustomerSubscriptionCategories200ResponseDataInner = SmartCommSDKAPI.GetCustomerSubscriptionCategories200ResponseDataInner

extension SmartCommSDKAPI {

public struct GetCustomerSubscriptionCategories200ResponseDataInner: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var id: String?
    public var attributes: GetCustomerSubscriptionCategories200ResponseDataInnerAttributes?
    public var links: GetCustomerSubscriptionCategories200ResponseDataInnerLinks?

    public init(type: String? = nil, id: String? = nil, attributes: GetCustomerSubscriptionCategories200ResponseDataInnerAttributes? = nil, links: GetCustomerSubscriptionCategories200ResponseDataInnerLinks? = nil) {
        self.type = type
        self.id = id
        self.attributes = attributes
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case attributes
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encodeIfPresent(links, forKey: .links)
    }
}

}
