//
// LogPushEvent400Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.LogPushEvent400Response")
public typealias LogPushEvent400Response = SmartCommSDKAPI.LogPushEvent400Response

extension SmartCommSDKAPI {

public struct LogPushEvent400Response: Codable, JSONEncodable, Hashable {

    public var errors: [LogPushEvent400ResponseErrorsInner]?

    public init(errors: [LogPushEvent400ResponseErrorsInner]? = nil) {
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
    }
}

}
