//
// LogPushEvent400ResponseErrorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.LogPushEvent400ResponseErrorsInner")
public typealias LogPushEvent400ResponseErrorsInner = SmartCommSDKAPI.LogPushEvent400ResponseErrorsInner

extension SmartCommSDKAPI {

public struct LogPushEvent400ResponseErrorsInner: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var status: Int?

    public init(title: String? = nil, status: Int? = nil) {
        self.title = title
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

}
