//
// ModifyCustomerSubscriptionCategoriesRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.ModifyCustomerSubscriptionCategoriesRequestDataAttributes")
public typealias ModifyCustomerSubscriptionCategoriesRequestDataAttributes = SmartCommSDKAPI.ModifyCustomerSubscriptionCategoriesRequestDataAttributes

extension SmartCommSDKAPI {

public struct ModifyCustomerSubscriptionCategoriesRequestDataAttributes: Codable, JSONEncodable, Hashable {

    public var categories: ModifyCustomerSubscriptionCategoriesRequestDataAttributesCategories?

    public init(categories: ModifyCustomerSubscriptionCategoriesRequestDataAttributesCategories? = nil) {
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categories, forKey: .categories)
    }
}

}
