//
// ModifyCustomerSubscriptionCategoriesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.ModifyCustomerSubscriptionCategoriesRequest")
public typealias ModifyCustomerSubscriptionCategoriesRequest = SmartCommSDKAPI.ModifyCustomerSubscriptionCategoriesRequest

extension SmartCommSDKAPI {

public struct ModifyCustomerSubscriptionCategoriesRequest: Codable, JSONEncodable, Hashable {

    public var data: ModifyCustomerSubscriptionCategoriesRequestData?

    public init(data: ModifyCustomerSubscriptionCategoriesRequestData? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
