//
// SetCustomerNotificationStatusRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.SetCustomerNotificationStatusRequest")
public typealias SetCustomerNotificationStatusRequest = SmartCommSDKAPI.SetCustomerNotificationStatusRequest

extension SmartCommSDKAPI {

public struct SetCustomerNotificationStatusRequest: Codable, JSONEncodable, Hashable {

    public var data: SetCustomerNotificationStatusRequestData?

    public init(data: SetCustomerNotificationStatusRequestData? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
