//
// SetCustomerNotificationStatus200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.SetCustomerNotificationStatus200Response")
public typealias SetCustomerNotificationStatus200Response = SmartCommSDKAPI.SetCustomerNotificationStatus200Response

extension SmartCommSDKAPI {

public struct SetCustomerNotificationStatus200Response: Codable, JSONEncodable, Hashable {

    public var data: SetCustomerNotificationStatus200ResponseData?

    public init(data: SetCustomerNotificationStatus200ResponseData? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
