//
// AddCustomerContactTokenRequestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.AddCustomerContactTokenRequestData")
public typealias AddCustomerContactTokenRequestData = SmartCommSDKAPI.AddCustomerContactTokenRequestData

extension SmartCommSDKAPI {

public struct AddCustomerContactTokenRequestData: Codable, JSONEncodable, Hashable {

    public var attributes: AddCustomerContactTokenRequestDataAttributes?

    public init(attributes: AddCustomerContactTokenRequestDataAttributes? = nil) {
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
