//
// AddCustomerContactTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.AddCustomerContactTokenRequest")
public typealias AddCustomerContactTokenRequest = SmartCommSDKAPI.AddCustomerContactTokenRequest

extension SmartCommSDKAPI {

public struct AddCustomerContactTokenRequest: Codable, JSONEncodable, Hashable {

    public var data: AddCustomerContactTokenRequestData?

    public init(data: AddCustomerContactTokenRequestData? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
