//
// GenerateAccessTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GenerateAccessTokenRequest")
public typealias GenerateAccessTokenRequest = SmartCommSDKAPI.GenerateAccessTokenRequest

extension SmartCommSDKAPI {

public struct GenerateAccessTokenRequest: Codable, JSONEncodable, Hashable {

    public var data: GenerateAccessTokenRequestData?

    public init(data: GenerateAccessTokenRequestData? = nil) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

}
