//
// GenerateAccessTokenRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.GenerateAccessTokenRequestDataAttributes")
public typealias GenerateAccessTokenRequestDataAttributes = SmartCommSDKAPI.GenerateAccessTokenRequestDataAttributes

extension SmartCommSDKAPI {

public struct GenerateAccessTokenRequestDataAttributes: Codable, JSONEncodable, Hashable {

    public var username: String?
    public var password: String?

    public init(username: String? = nil, password: String? = nil) {
        self.username = username
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(password, forKey: .password)
    }
}

}
