//
// ModifyCustomerSubscriptionCategoriesRequestDataAttributesCategoriesMailingCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.ModifyCustomerSubscriptionCategoriesRequestDataAttributesCategoriesMailingCode")
public typealias ModifyCustomerSubscriptionCategoriesRequestDataAttributesCategoriesMailingCode = SmartCommSDKAPI.ModifyCustomerSubscriptionCategoriesRequestDataAttributesCategoriesMailingCode

extension SmartCommSDKAPI {

public struct ModifyCustomerSubscriptionCategoriesRequestDataAttributesCategoriesMailingCode: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var sms: String?
    public var push: String?
    public var messengertelegram: String?
    public var messengerwhatsapp: String?

    public init(email: String? = nil, sms: String? = nil, push: String? = nil, messengertelegram: String? = nil, messengerwhatsapp: String? = nil) {
        self.email = email
        self.sms = sms
        self.push = push
        self.messengertelegram = messengertelegram
        self.messengerwhatsapp = messengerwhatsapp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case sms
        case push
        case messengertelegram = "messenger:telegram"
        case messengerwhatsapp = "messenger:whatsapp"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(sms, forKey: .sms)
        try container.encodeIfPresent(push, forKey: .push)
        try container.encodeIfPresent(messengertelegram, forKey: .messengertelegram)
        try container.encodeIfPresent(messengerwhatsapp, forKey: .messengerwhatsapp)
    }
}

}
