//
// SetCustomerNotificationStatus200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "SmartCommSDKAPI.SetCustomerNotificationStatus200ResponseData")
public typealias SetCustomerNotificationStatus200ResponseData = SmartCommSDKAPI.SetCustomerNotificationStatus200ResponseData

extension SmartCommSDKAPI {

public struct SetCustomerNotificationStatus200ResponseData: Codable, JSONEncodable, Hashable {

    public var attributes: SetCustomerNotificationStatus200ResponseDataAttributes?

    public init(attributes: SetCustomerNotificationStatus200ResponseDataAttributes? = nil) {
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

}
